name: Build sd-scripts CUDA126 bundle

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Clone sd-scripts
        run: |
          git clone https://github.com/kohya-ss/sd-scripts.git
        shell: powershell

      - name: Create virtual environment
        run: |
          cd sd-scripts
          python -m venv venv
        shell: powershell

      - name: Install PyTorch CUDA 12.6
        run: |
          cd sd-scripts
          .\venv\Scripts\activate
          python -m pip install --upgrade pip

          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126
        shell: powershell

      - name: Install dependencies
        run: |
          cd sd-scripts
          .\venv\Scripts\activate
          pip install -r requirements.txt
        shell: powershell

      - name: Install xformers
        run: |
          cd sd-scripts
          .\venv\Scripts\activate
          pip install xformers --extra-index-url https://download.pytorch.org/whl/cu126
        shell: powershell

      - name: Create archive
        run: |
          Compress-Archive -Path sd-scripts -DestinationPath sd_scripts_cuda126.zip
        shell: powershell

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sd_scripts_cuda126
          path: sd_scripts_cuda126.zip
